apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: netology-task
spec:
  selector:
    app: nginx-multitool
  ports:
  - name: nginx-port
    port: 80
    targetPort: 80
    nodePort: 32000
  - name: multitool-port
    port: 8080
    targetPort: 1180
    nodePort: 32001
  type: NodePort
