apiVersion: v1
kind: Service
metadata:
  name: cluster-service
  namespace: netology-task
spec:
  selector:
    app: nginx-multitool  # Совпадает с меткой Deployment
  ports:
    - name: nginx-port
      port: 9001
      targetPort: 80  # Порт контейнера nginx
    - name: multitool-port
      port: 9002
      targetPort: 1180  # Порт контейнера multitool
  type: ClusterIP
