apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: netology-task
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool
    command: ["/bin/sh", "-c"]
    args: ["sleep infinity"]
